### ISSUE TITLE
Web deployment not working

### ISSUE THREAD

**Issue by mUmarBaloch** [shessafridi/vidly-flutter#1]
blank page in web deployment.

**Comment by shessafridi** [comment]
Working in edge, not working in chrome for some reason
![image](https://user-images.githubusercontent.com/59542111/135724696-e146a8dc-5122-4f40-901e-58da03dadb1c.png)

**Comment by mUmarBaloch** [comment]
Alright.

**Comment by shessafridi** [comment]
@mUmarBaloch Updating Chrome to the latest version fixes the issue.
